name: PulseraWatch
options:
  bundleIdPrefix: com.pulsera
  deploymentTarget:
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  Pulsera Watch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: "Pulsera Watch"
        excludes:
          - "Info.plist"
    info:
      path: "Pulsera Watch/Info.plist"
      properties:
        WKApplication: true
        WKWatchOnly: true
        NSHealthShareUsageDescription: "Pulsera needs access to your heart rate and heart rate variability data to monitor your safety in real time and alert your community if anomalies are detected."
        NSHealthUpdateUsageDescription: "Pulsera records health metrics to provide continuous safety monitoring and anomaly detection for your community group."
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pulsera.watchapp
        PRODUCT_NAME: "Pulsera Watch"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: "Pulsera Watch/Pulsera Watch.entitlements"
